"""Set initial Database

Revision ID: 4959dec978a1
Revises: 
Create Date: 2019-12-11 13:18:14.323560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4959dec978a1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesson',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('subname', sa.String(length=255), nullable=False),
    sa.Column('duration', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', name='lessonstatus'), server_default='DRAFT', nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lesson'))
    )
    op.create_table('user',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('surname', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('picture', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('email', name=op.f('uq_user_email'))
    )
    op.create_table('application_user',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('user_type', sa.Enum('ADMINISTRATOR', 'USER', 'TEACHER', name='usertype'), server_default='USER', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_application_user_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_application_user')),
    sa.UniqueConstraint('username', name=op.f('uq_application_user_username'))
    )
    op.create_index(op.f('ix_application_user_user_id'), 'application_user', ['user_id'], unique=False)
    op.create_table('card',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('lesson_id', sa.String(length=36), nullable=False),
    sa.Column('text', sa.BLOB(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], name=op.f('fk_card_lesson_id_lesson'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_card'))
    )
    op.create_index(op.f('ix_card_lesson_id'), 'card', ['lesson_id'], unique=False)
    op.create_table('lesson_user',
    sa.Column('lesson_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('INPROGRESS', 'FINISHED', name='userlessonstatus'), server_default='INPROGRESS', nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], name=op.f('fk_lesson_user_lesson_id_lesson'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_lesson_user_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('lesson_id', 'user_id', name=op.f('pk_lesson_user')),
    sa.UniqueConstraint('lesson_id', 'user_id', name='_lesson_user_unique')
    )
    op.create_index(op.f('ix_lesson_user_status'), 'lesson_user', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lesson_user_status'), table_name='lesson_user')
    op.drop_table('lesson_user')
    op.drop_index(op.f('ix_card_lesson_id'), table_name='card')
    op.drop_table('card')
    op.drop_index(op.f('ix_application_user_user_id'), table_name='application_user')
    op.drop_table('application_user')
    op.drop_table('user')
    op.drop_table('lesson')
    # ### end Alembic commands ###
